### ISSUE TITLE
Lutris 5.0 core dumped

### ISSUE THREAD

**Issue by IanTrudel** [jatin-cbs/Lutris-RHEL-CentOS7#1] opened 2019-02-12 01:44 UTC
Lutris 5.0 core dumped after fresh install. Please, take note that Lutris 4.23 package is working fine.

`
(lutris:25114): Gtk-ERROR **: 20:40:20.997: failed to add UI: L’ouverture du fichier « /usr/share/lutris/ui/menus-traditional.ui » a échoué : Aucun fichier ou dossier de ce type
[1]    25114 trace trap (core dumped)  lutris
`

**Comment by Saladin1812** [comment] 2019-02-12 05:21
Can you run lutris -d and send the logs ?

**Comment by Saladin1812** [comment] 2019-02-12 05:31
bug confirmed, few same posts on reddit.

**Comment by Saladin1812** [comment] 2019-02-12 06:27
I just updated the RPM make sure you have EPEL enabled on centOS/RHEL

**Comment by Saladin1812** [comment] 2019-02-12 06:30
Tell me if its working now..

**Comment by IanTrudel** [comment] 2019-02-14 17:29
`
--> Résolution des dépendances terminée
Erreur : Paquet : lutris-0.5.0.1-4.el7.x86_64 (/lutris-0.5.0.1-4.el7.x86_64)
             Requiert : mesa-vulkan-drivers(x86-32)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest
`

It requires **mesa-vulkan-drivers** but my system runs with the Nvidia proprietary driver.

**Comment by Saladin1812** [comment] 2019-02-15 09:07
ah now i got the issue mesa-vulkan-driver 32 bit is not on centOS i add that in script wait.

**Comment by Saladin1812** [comment] 2019-02-15 09:16
I do have to keep changing this script as lutris now dont have a "noarch" package like 4.x versions. So i have to configure all dependencies.

**Comment by Saladin1812** [comment] 2019-02-15 09:20
Try this for now i re created RPM, or else when noarch package of lutris 5.0 is available It will be easy to create RPM like in 4.x packages they are noarch so compatible with all architectures. in FC 29 they currently dont have noarch packages.

**Comment by IanTrudel** [comment] 2019-02-16 19:29
I did try the latest RPM but it core dumped again with the message.

**Comment by Saladin1812** [comment] 2019-02-18 13:41
Ok I will take noarch package when its available until then i will create.. putting this in readme for now

**Comment by IanTrudel** [comment] 2019-02-18 18:11
Thank you. Keep up with the good work! :D

**Comment by Saladin1812** [comment] 2019-02-28 18:21
After some investigation there are somethings needed by lutris 5.0 which are not in centOS 7 but are there in RHEL 8 beta so RHEL 8 and CentOS will work fine when they release. I guess 4.23 will be last version i will be able to create for centOS 7. I will try bundling dependencies for 5.0 for centos on to new branch on github and try all the stuff there.

**Comment by IanTrudel** [comment] 2019-03-06 11:36
Any progress on 5.0 for CentOS 7? :)

**Comment by Saladin1812** [comment] 2019-03-11 16:32
there are many dependencies not present in centos 7 for lutris 5.x, if I think off bundling soo many dependencies it will no longer be an rpm package but i might have to create a full .sh script. Lutris 5.0 will be working on centos 8 or RHEL 8 predicted to release in April or may. So lets see.

**Comment by IanTrudel** [comment] 2019-03-15 04:26
(just a note: https://github.com/lutris/lutris/issues/1855)

**Comment by IanTrudel** [comment] 2019-03-21 05:17
@jatin-cbs I talked with the man behind Lutris and he suggested that you make a pull request on Lutris to provide support for CentOS. It is worth looking into it.

**Comment by Saladin1812** [comment] 2019-03-26 15:47
Yes i have talked to @strycore but 4.x is depreciated despite everything runs fine using lutris 4.23 and its just UI and few things different i wont make as 5.x wont run on centOS due to few python dependencies. That is why he has said that once 5.x is ready i open pull request but it wont run..

**Comment by Saladin1812** [comment] 2019-03-26 15:50
4.23 can run all games that 5.x can do so i dont see a reason not to support the rpm but, i cant do anything..

**Comment by Saladin1812** [comment] 2019-03-26 15:53
I will build latest 5.x version once RHEL 8 comes out. It has all deps.

**Comment by IanTrudel** [comment] 2019-03-27 20:58
What are the hurdles to get 5.0 working on CentOS at the moment? Getting the python dependencies shouldn't be too much troubles though.

**Comment by strycore** [comment] 2019-03-27 22:14
is it possible to have the CentOS specific changes incorporated in the project's lutris.spec file as a PR or is it too different? Also, what Python dependencies are missing in CentOS?

**Comment by Saladin1812** [comment] 2019-03-28 11:44
no spec file is not much different as its rebuild of the lutris fedora RPM @strycore . python pillow is not avialable on centOS 7 im trying to bundle dependencies, create a whole new repo. 4.23 is working as it didnt had those dependencies. I am still trying for it to work out of the box. I will create a development branch here next week hopefully..

**Comment by IanTrudel** [comment] 2019-03-28 15:47
> python pillow is not avialable on centOS 7

`yum search pillow` shows a few entries. Any of those would be adequate?

**Comment by Saladin1812** [comment] 2019-03-28 16:18
no nothing is :( even I installed pillow using pip but that wont work, lutris may be unable to find the one installed with pip. I will open dev branch so i can get help.

**Comment by Saladin1812** [comment] 2019-03-29 16:42
![Screenshot from 2019-03-29 22-11-23](https://user-images.githubusercontent.com/40650341/55248347-9f5c8900-526f-11e9-9d40-bc84de67b9e0.png)

As python 3 pillow is not avaiable its showing the PIL import error while launching lutris.

**Comment by Saladin1812** [comment] 2019-03-29 16:47
python 3 pillow is the main issue, currently trying using pip..

**Comment by Saladin1812** [comment] 2019-03-29 17:30
@strycore @BackOrder I have managed to resolve all dependencies using pip to install pillow and it worked now its able to find pillow, but on launch these the logs it never opens..

![Screenshot from 2019-03-29 22-58-59](https://user-images.githubusercontent.com/40650341/55251318-493f1400-5276-11e9-9883-17c78dff7955.png)
it seems something in lutris/gui/application.py, line 333

**Comment by Saladin1812** [comment] 2019-03-29 17:40
its actually exactly same to this error https://github.com/lutris/lutris/issues/1366

**Comment by Saladin1812** [comment] 2019-03-29 17:43
trying different lutris version 5.1.2 maybe..

**Comment by Saladin1812** [comment] 2019-03-29 18:07
![Screenshot from 2019-03-29 23-36-47](https://user-images.githubusercontent.com/40650341/55253519-9376c400-527b-11e9-96f6-8e17d7264a02.png)

**Comment by Saladin1812** [comment] 2019-03-29 18:08
Success finaly :) posting the commands please test and report back @BackOrder and others..

**Comment by Saladin1812** [comment] 2019-03-29 18:15
Follow the readme on the new branch @BackOrder @strycore pip instructions :) if it works closing this issue.

**Comment by IanTrudel** [comment] 2019-03-29 19:39
It's not working just yet here though there is a different problem now. It coredumps right after looking for GPU driver.

By the way, I recommend `cp -Rv /usr/lib/python3.7/site-packages/lutris /usr/lib/python3.4/site-packages/` instead of `mv`.

log:
```
2019-03-29 15:36:24,547: Running Lutris 0.5.1.2
2019-03-29 15:36:24,548: Using NVIDIA drivers 418.30 for x86_64
2019-03-29 15:36:24,548: GPU: GeForce GTX 660M
2019-03-29 15:36:24,548: GPU: 10DE:0FD4 1043:2115 using nvidia drivers
[1]    5652 segmentation fault (core dumped)  lutris
```

**Comment by IanTrudel** [comment] 2019-03-29 19:45
> By the way, I recommend cp -Rv /usr/lib/python3.7/site-packages/lutris /usr/lib/python3.4/site-packages/ instead of mv.

Or, better yet, `ln` the thing. :)

**Comment by Saladin1812** [comment] 2019-03-29 19:57
Strange its working on my system and even the previous script that was back here when this issue was created it never showed me core dumped, it just show the PIL error for pillow which i fixed today.. It can be a nvida driver problem I will test this on my other machine which has 1050ti tommorow maybe.. Thanks for the suggestion tho @BackOrder

**Comment by Saladin1812** [comment] 2019-03-29 20:00
which centos version are you using ?

**Comment by IanTrudel** [comment] 2019-03-29 20:01
CentOS 7. Here is the `uname -a`: `Linux ###### 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Saladin1812** [comment] 2019-03-29 20:06
7.6 ? try another nvidia driver version 415.. I was just searching core dump error after nvidia drivers installation on google.. Actually not google duckduckgo lets respect privacy XD

**Comment by IanTrudel** [comment] 2019-03-29 20:11
Uh? Do you mean installing an older version of the driver? o_O

**Comment by Saladin1812** [comment] 2019-03-29 20:11
Did you blacklisted noveau when you installed the drivers ?

**Comment by Saladin1812** [comment] 2019-03-29 20:12
Just misclicked ...

**Comment by IanTrudel** [comment] 2019-03-29 20:12
> Did you blacklisted noveau when you installed the drivers ?

Obviously. My system is well maintained. Shouldn't be any such troubles here.

**Comment by Saladin1812** [comment] 2019-03-29 20:18
Run using lutris -d

**Comment by IanTrudel** [comment] 2019-03-29 20:19
We will eventually get it working. :)

Here as you requested.
```
INFO     2019-03-29 15:37:15,295 [application.do_command_line:219]:Running Lutris 0.5.1.2
INFO     2019-03-29 15:37:15,296 [startup.check_driver:55]:Using NVIDIA drivers 418.30 for x86_64
INFO     2019-03-29 15:37:15,296 [startup.check_driver:59]:GPU: GeForce GTX 660M
INFO     2019-03-29 15:37:15,296 [startup.check_driver:76]:GPU: 10DE:0FD4 1043:2115 using nvidia drivers
[1]    8351 segmentation fault (core dumped)  lutris -d
```

**Comment by Saladin1812** [comment] 2019-03-29 20:20
This is actually my guess i have actually had issue with steam back then core dumped error on nvidia drivers.. So i removed drivers installed steam and then the drivers which worked.. I think this can be the same issue..

**Comment by Saladin1812** [comment] 2019-03-29 20:22
Why centos doesnt have a nvidia repo i hope it does in 8 using rpm fusion manual drivers with dkms cause problems.

**Comment by Saladin1812** [comment] 2019-03-29 20:23
i will be able to help you tommorow when i try it on nvidia machine i gota to to sleep for now i failed in economics XD i have my retest on monday jesus !

**Comment by IanTrudel** [comment] 2019-03-29 20:25
The problem is either `mv` or `cp -Rv` will copy things over existing files in `/usr/lib/python3.4/site-packages/` but some remaining files from the previous version are lingering on.

The solution is really to remove any existing directory and symlink.

`ln -s /usr/lib/python3.7/site-packages/lutris /usr/lib/python3.4/site-packages/lutris`

![Capture d’écran de 2019-03-29 16-24-55](https://user-images.githubusercontent.com/8844578/55260616-38bf7700-523f-11e9-8832-23e177dc281b.png)

**Comment by Saladin1812** [comment] 2019-03-29 20:36
It worked for u ?

**Comment by IanTrudel** [comment] 2019-03-29 20:38
Yes, sir! Thank you for your help.

**Comment by Saladin1812** [comment] 2019-03-29 20:40
I have updated the readme 😊 thanks !

**Closed as completed by Saladin1812** 2019-03-29 20:40 UTC
Labels: bug

**Comment by strycore** [comment] 2019-03-30 02:27
the pillow dependency can be made optional

**Comment by Saladin1812** [comment] 2019-03-30 04:52
https://github.com/jatin-cbs/Lutris-RHEL-CentOS7/issues/1#issuecomment-478067593

PIL error comes when not having pillow so i fixed it using pip.

**Comment by strycore** [comment] 2019-03-30 04:56
yeah, PIL and pillow are the same thing.
The only component using that currently is the background for the sidebar. We can use feature detection to not display a background if PIL isn't available, it's not a very hard patch

**Comment by strycore** [comment] 2019-03-30 04:57
i'd rather make the background optional than add steps with pip in the lutris.spec, that's what I'm saying.

**Comment by Saladin1812** [comment] 2019-03-30 04:59
That wont be needed now im workin on new RPM that uses python 3.6 which has all deps avilable.. @strycore

**Comment by strycore** [comment] 2019-03-30 05:01
yeah but how would that be distributed? Will it be in some kind of CentOS PPA equivalent? or can I use your changes in OBS and distribute the packages there?

**Comment by Saladin1812** [comment] 2019-03-30 07:21
There is a third party Repo called "IUS repos" in centos which actually has python3.6 packages required for lutris 5 and there are pip commands.. I dont know how to include pip commands in an RPM tho. So currently you have to do these two things manualy other things are handeled by the RPM.. Yes u can distribute as a PPA kind off for centos but what about the pip packages that is the thing to do manually.. @strycore

**Comment by Saladin1812** [comment] 2019-03-30 07:23
For now you can include this on lutris website given by install instructions on the readme @strycore

**Comment by Saladin1812** [comment] 2019-03-30 07:27
or simply provide this link to follow instructions https://github.com/jatin-cbs/Lutris-RHEL-CentOS7/

**Comment by Saladin1812** [comment] 2019-03-30 07:49
4.23 RPM  it is stable working and doesnt need anything manually except creating 1 symlink as in readme https://github.com/jatin-cbs/Lutris-RHEL-CentOS7/tree/master
